package.json, src/common/utxobased/network/BlockBook.ts, src/common/utxobased/plugin/UtxoEngineState.ts, src/common/utxobased/plugin/makeUtxoEngine.ts, yarn.lock
It: 
* Fetches the latest block height by grabbing the server info
* Removes axios as a dependency
=> Fetch latest block height and remove axios

package.json, src/common/utxobased/db/Processor.ts, src/common/utxobased/plugin/makeUtxoEngine.ts, yarn.lock
It:
* Uses an updated version of baselet's RangeBase to paginate values.
* Fixes the implementation of fetching transactions.
=> Fix fetch transactions implementation

src/common/utxobased/keymanager/keymanager.ts, src/common/utxobased/keymanager/utxopicker/types.ts
It:
* Reverts incorrect changes that were made to the keymanager
=> Revert keymanager

src/common/utxobased/db/Models/baselet.ts, src/common/utxobased/db/makeProcessor.ts
It slightly modifies the db return types and bucket sizes.
=> Update processor db return types

src/common/plugin/types.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/keymanager/keymanager.ts
Able to get the fresh address of any branch instead of just the change.
=> Get Fresh Address

package.json, src/common/plugin/types.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/keymanager/keymanager.ts, src/common/utxobased/network/Socket.ts, yarn.lock
It upgrades the packages edge-core-js and baselet.
=> Upgrade Packages

src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts
It returns the public and legacy address from the keymanager.
=> Update UTXO Wallet Tools API

src/common/utxobased/engine/utils.ts, src/common/utxobased/keymanager/keymanager.ts
Adds a BIP type to recognize the old Airbitz account derivation.
=> Add Airbitz BIP type

src/common/utxobased/db/makeProcessor.ts
The data needed to update a transaction is limited to specific parameters of a transaction.
=> Update Transaction Using Partial Data

src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/network/BlockBook.ts
It fixes errors caused by TypeScript.
=> Fixing Typing Errors

src/common/utxobased/engine/constants.ts, src/common/utxobased/engine/makeUtxoEngineState.ts
Adds the engine callback while processing address to keep track of the progress.
=> Check Address Checked Progress

src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts
It implements the functionality to add gap limit addresses from the engine API to the database.
=> AddGapLimitAddresses

src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/utils.ts
It implements the UTXO Engine function `getDisplayPrivateKey` function.
=> Display Private Key

src/common/plugin/makeCurrencyTools.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts, src/common/utxobased/engine/utils.ts
Implements the UTXO Engine function `getDisplayPublicSeed` function.
=> Display Public Seed

src/common/utxobased/engine/makeUtxoEngineState.ts
This fixes the logic to get the last used address index. It was testing against the previous index that it found to be marked as `used` instead of testing against the current index it is iterating over.
=> Mismatch Public Address

src/common/utxobased/db/makeProcessor.ts
It allows fetching transaction by a combination of the options passed in by the engine.
=> API Fix for getTransaction

src/common/utxobased/db/makeProcessor.ts
It adds a try/catch when adding a duplicate index into the UTXO database.
=> Duplicate UTXO Index Catch

src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/network/BlockBook.ts, src/common/utxobased/network/BlockBookAPI.ts, src/common/utxobased/network/Deferred.ts, src/common/utxobased/network/Socket.ts, src/common/utxobased/network/nodejsWS.ts, test/common/utxobased/network/BlockBook.spec.ts
See comments in: https://github.com/EdgeApp/edge-currency-plugins/pull/103
=> Pick next task new

src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/network/Socket.ts
Various patches following the pick next task pull request.
=> Pick next task patches

src/common/constants.ts, src/common/plugin/makeCurrencyTools.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts, src/common/utxobased/engine/paymentRequest.ts, src/common/utxobased/keymanager/base.ts, src/common/utxobased/keymanager/bitcoincashUtils/base32.ts, src/common/utxobased/keymanager/bitcoincashUtils/bn.ts, src/common/utxobased/keymanager/bitcoincashUtils/cashAddress.ts, src/common/utxobased/keymanager/bitcoincashUtils/checkdatasig.ts, src/common/utxobased/keymanager/keymanager.ts, src/common/utxobased/network/Deferred.ts, src/common/utxobased/network/socketQueue.ts, src/types.ts, test/common/plugin/currencyPlugins.spec.ts, test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts, test/utils.ts
Includes fixes for current linting errors exposed by `yarn lint` and follow-up fixes for https://github.com/EdgeApp/edge-currency-plugins/pull/89 .
=> Lint the code again

src/common/utxobased/db/makeMutex.ts, src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, test/common/utxobased/db/Processor.spec.ts
Add a mutex to all processor functions reading or writing on the database.
=> Full processor mutex

src/common/plugin/makeCurrencyPlugin.ts, src/common/plugin/pluginState.ts, src/common/utxobased/engine/makeServerStates.ts, src/common/utxobased/info/bitcoin.ts, src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/feathercoin.ts, src/common/utxobased/info/litecoin.ts, src/common/utxobased/info/zcoin.ts, src/common/utxobased/network/BlockBook.ts, test/common/utxobased/network/BlockBook.spec.ts
Fixup to the previous pull request
=> Add block book servers

src/btc.ts, src/common/plugin/makeCurrencyPlugin.ts, src/common/plugin/makeCurrencyTools.ts, src/common/plugin/types.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts, src/common/utxobased/info/all.ts, src/common/utxobased/info/bitcointestnet.ts
=> Testnet Support

fixtures/currencyPlugins.json, test/common/plugin/currencyPlugins.spec.ts, test/utils.ts
- xpub derivation tests are still disabled
more dummy data was added
=> Add full plugin test

src/common/plugin/makeEngineEmitter.ts, src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, test/common/utxobased/db/Processor.spec.ts
Connects the new processor with the engine. Needs another rebase once pending pull requests are merged.
=> New processor integration

src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, test/common/utxobased/db/Processor.spec.ts
Replaces: https://github.com/EdgeApp/edge-currency-plugins/pull/180 (includes minor cleanup)
=> Processor address fixups

package.json
Do type checking along with linting on pre-commit.
=> Add precommit script for pre-commit hook

src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/db/types.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, test/common/utxobased/db/Processor.spec.ts
Replaces: https://github.com/EdgeApp/edge-currency-plugins/pull/184
=> Grab blockHeight before address query and save height query results

src/common/plugin/pluginState.ts
The problem addressed with this commit is that the
`disableFetchingServers` currency info flag would halt the `fetchServer`
method completely.
The `fetchServer` method was also responsible for saving the server
list whether that's the default list or from the info server.
The solution is to refactor the parts in `fetchServer` routine which
saves the server list to a new `refreshServers` method for better
separation of concerns.
=> Fix disableFetchingServers

src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts, src/common/utxobased/keymanager/keymanager.ts
This fixes all the thrown errors during a spend on BCH caused by broken implementation.
=> Sam/Fix/Spend Errors

package.json, yarn.lock
Replaces: https://github.com/EdgeApp/edge-currency-plugins/pull/154
Waiting to merge until stability without this change is achieved.
=> Upgrade memlet to v0.1.1

src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201376972471949
=> Sam/Fix/Zero Balance TX

src/common/utxobased/engine/makeUtxoEngine.ts
---
- https://app.asana.com/0/0/1201429782598577
=> Fix getDisplayPrivateSeed

src/common/utxobased/engine/makeUtxoEngine.ts, src/util/unixTime.ts
---
- https://app.asana.com/0/0/1201440393197228
=> Fix Moon Walker Bug

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201481239201205
=> Sam/Fix Double Balance

src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/types.ts
---
- https://app.asana.com/0/0/1201447744301902
=> Sam/Fix Zero-Amount After Send

src/common/plugin/makeCurrencyPlugin.ts, src/common/plugin/pluginState.ts, src/common/plugin/utils.ts, src/common/utxobased/info/badcoin.ts, src/common/utxobased/info/bitcoin.ts, src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/info/bitcoincashtestnet.ts, src/common/utxobased/info/bitcoingold.ts, src/common/utxobased/info/bitcoingoldtestnet.ts, src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/bitcointestnet.ts, src/common/utxobased/info/dash.ts, src/common/utxobased/info/digibyte.ts, src/common/utxobased/info/dogecoin.ts, src/common/utxobased/info/eboost.ts, src/common/utxobased/info/feathercoin.ts, src/common/utxobased/info/groestlcoin.ts, src/common/utxobased/info/litecoin.ts, src/common/utxobased/info/qtum.ts, src/common/utxobased/info/ravencoin.ts, src/common/utxobased/info/smartcash.ts, src/common/utxobased/info/ufo.ts, src/common/utxobased/info/vertcoin.ts, src/common/utxobased/info/zcoin.ts
---
- https://app.asana.com/0/0/1201440393581347
=> Fix Custom Node Settings

src/common/plugin/types.ts, src/common/utxobased/engine/utils.ts, src/common/utxobased/info/badcoin.ts, src/common/utxobased/info/bitcoin.ts, src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/info/bitcoincashtestnet.ts, src/common/utxobased/info/bitcoingold.ts, src/common/utxobased/info/bitcoingoldtestnet.ts, src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/bitcointestnet.ts, src/common/utxobased/info/dash.ts, src/common/utxobased/info/digibyte.ts, src/common/utxobased/info/dogecoin.ts, src/common/utxobased/info/eboost.ts, src/common/utxobased/info/feathercoin.ts, src/common/utxobased/info/groestlcoin.ts, src/common/utxobased/info/litecoin.ts, src/common/utxobased/info/qtum.ts, src/common/utxobased/info/ravencoin.ts, src/common/utxobased/info/smartcash.ts, src/common/utxobased/info/ufo.ts, src/common/utxobased/info/vertcoin.ts, src/common/utxobased/info/zcoin.ts, src/common/utxobased/keymanager/keymanager.ts, src/util/indexAtProtected.ts, src/util/undefinedIfEmptyString.ts, test/common/utxobased/keymanager/coins/altcointestfixtures.ts, test/common/utxobased/keymanager/coins/keymanagertest.spec.ts, test/utils.ts
---
- https://app.asana.com/0/0/1201238254464027
=> Keymanager: Support multiple prefixes from the same coin

src/common/utxobased/keymanager/bitcoincashUtils/cashAddress.ts, test/common/utxobased/keymanager/coins/altcointestfixtures.ts, test/common/utxobased/keymanager/coins/cashaddr.spec.ts
Replaces https://github.com/EdgeApp/edge-currency-plugins/pull/254
---
- https://app.asana.com/0/0/1201440393197281
=> Do not show prefix on cash address

src/common/fees/makeFees.ts, src/common/plugin/types.ts, src/common/utxobased/db/Models/baselet.ts, src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/engine/makeUtxoWalletTools.ts, src/common/utxobased/keymanager/keymanager.ts, src/util/delay.ts, test/common/utxobased/engine/UtxoWalletTools.spec.ts
---
- https://app.asana.com/0/0/1201440626414086
=> Fix Sweep Private keys

src/common/utxobased/keymanager/keymanager.ts
---
- https://app.asana.com/0/0/1201543940386179
=> Cleanup Key Manager

src/common/utxobased/engine/makeServerStates.ts, src/common/utxobased/network/BlockBook.ts, src/common/utxobased/network/BlockBookAPI.ts
---
- https://app.asana.com/0/0/1201543940386172
=> Add error response type to blockbook cleaners

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201478895039831
=> Fix Spent UTXO Removal

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201517692265090
=> Fix TXs Stuck Pending

src/common/utxobased/info/digibyte.ts, test/common/utxobased/addressFormat/addressFormatIndex/fixtures.json, test/common/utxobased/keymanager/coins/altcointestfixtures.ts
---
- https://app.asana.com/0/0/1201499690620943
=> Add 0x05 legacy p2sh prefix for to digibyte's CoinInfo

src/common/plugin/types.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/info/groestlcoin.ts, src/common/utxobased/info/smartcash.ts, src/common/utxobased/keymanager/keymanager.ts
---
- https://app.asana.com/0/0/1201493443265388
=> Add txHashFunction serialization function to CoinInfo for GRS and SMART

src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/digibyte.ts, test/common/plugin/currencyPlugin.fixtures/common.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoinsv.ts, test/common/plugin/currencyPlugin.fixtures/currencies/digibyte.ts, test/common/utxobased/keymanager/coins/altcointestfixtures.ts
---
- https://app.asana.com/0/0/1201626137244258
=> Fix coinTypes

nodemon.json, package.json, yarn.lock
Use nodemon to watch and compile after source code changes.
=> Add `start.dev` script for local development

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201608598809059
=> Fix incorrect condition for "Airbitz" (bip32) wallet types

src/common/plugin/makeEngineEmitter.ts, src/common/plugin/types.ts, src/common/utxobased/engine/makeServerStates.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/network/BlockBook.ts, src/common/utxobased/network/BlockBookAPI.ts, src/common/utxobased/network/Socket.ts, test/common/utxobased/network/BlockBook.spec.ts
---
- https://app.asana.com/0/0/1201590067175759
=> Fix BCH Blockbook Syncing

src/common/plugin/makeCurrencyPlugin.ts, src/common/plugin/makeEngineEmitter.ts, src/common/plugin/pluginState.ts
---
- https://app.asana.com/0/0/1201681616582386
=> Sam/Minor Cleanups

src/common/plugin/makeCurrencyTools.ts, src/common/plugin/types.ts, src/common/utxobased/engine/utils.ts, src/common/utxobased/keymanager/keymanager.ts, test/common/plugin/currencyPlugin.fixtures/common.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoin.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoincash.ts, test/common/utxobased/addressFormat/addressFormatIndex/addressFormat.spec.ts
---
- https://app.asana.com/0/0/1201653637448502
=> Add support for Ren Bridge URIs

src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/keymanager/cleaners.ts, test/common/utxobased/engine/engine.spec.ts
---
- https://app.asana.com/0/0/1201510699681119
=> Disable bech32/bip84 wallet types

src/common/utxobased/db/Models/baselet.ts, src/common/utxobased/db/makeBaselets.ts, src/common/utxobased/db/makeProcessor.ts, test/common/utxobased/db/Processor.spec.ts
---
- https://app.asana.com/0/0/1201681616893842
=> Fix local database configuration

src/common/utxobased/engine/makeServerStates.ts, src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1201517692265090
=> Fix Transactions Stuck Pending

src/common/utxobased/network/Socket.ts, src/common/utxobased/network/socketQueue.ts
---
- https://app.asana.com/0/0/1201745119576227
=> Sweep Private Key Performance Fix

src/common/plugin/makeCurrencyTools.ts, src/common/utxobased/keymanager/cleaners.ts, test/common/plugin/currencyPlugin.fixtures/common.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoin.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoincash.ts, test/common/plugin/currencyPlugin.fixtures/currencies/bitcoinsv.ts, test/common/plugin/currencyPlugin.fixtures/currencies/digibyte.ts, test/common/plugin/currencyPlugin.fixtures/currencies/feathercoin.ts, test/common/plugin/currencyPlugin.fixtures/currencies/groestlcoin.ts, test/common/plugin/currencyPlugin.fixtures/currencies/litecoin.ts, test/common/plugin/currencyPlugin.fixtures/currencies/smartcash.ts, test/common/plugin/currencyPlugin.fixtures/currencies/zcoin.ts, test/common/plugin/currencyPlugin.spec.ts
---
- https://app.asana.com/0/0/1201689776652872
=> Implement `importPrivateKey`

src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/qtum.ts, src/common/utxobased/info/ravencoin.ts
---
- https://app.asana.com/0/0/1201681616893840
=> Add BSV, RVN, QTUM blockbook servers

src/common/utxobased/info/zcoin.ts
---
- https://app.asana.com/0/0/1201914705276084
=> Fix FIRO blockbook server URL

src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/info/bitcoincashtestnet.ts
---
- https://app.asana.com/0/0/1201914705276069
=> Fix Bitcoin SV currency name in Bitcoin Cash's fork list

src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/keymanager/keymanager.ts, test/common/utxobased/keymanager/coins/bitcoincashtransactiontest.spec.ts
---
- https://app.asana.com/0/0/1201869737454527
=> Replay Protection Fixes

src/common/utxobased/engine/makeUtxoEngine.ts
---
- https://app.asana.com/0/0/1201914705276084
=> Fix refreshServers/startEngine race condition

src/common/fees/makeFees.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/types.ts, src/common/utxobased/keymanager/keymanager.ts, test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts
https://user-images.githubusercontent.com/4012041/171945817-5bf7dccc-118e-4052-b01e-5d66776dc211.mov
---
- https://app.asana.com/0/0/1202369707618471
=> Payment Protocol Fixes

src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/keymanager/keymanager.ts
---
- https://app.asana.com/0/0/1201924982952957
=> Add default UTXO sorting based on value and confirmation status

src/common/utxobased/engine/makeUtxoEngine.ts
---
- https://app.asana.com/0/0/1202476488525226
=> Fix `InsufficientFundsError` condition in makeSpend

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1202817248343315
=> WIP Always delete a UTXO that's missing from the network

src/common/utxobased/engine/makeUtxoEngineState.ts
---
- https://app.asana.com/0/0/1200737202854160
- https://app.asana.com/0/0/1202812969533434
=> Fix broken transaction processing for txs with Taproot inputs

src/common/plugin/makeEngineEmitter.ts, src/common/plugin/makeMetadata.ts, src/common/plugin/types.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, test/common/plugin/makeMetadata.spec.ts
---
- https://app.asana.com/0/0/1203093844594819
=> New wallet balance calculation algorithm

package.json, src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, yarn.lock
This is blocked on PR https://github.com/EdgeApp/edge-core-js/pull/489 which needs to be merged and published and this PR will need an upgrade of the core before merge
---
- https://app.asana.com/0/0/1203395121961365
=> Features needed for Thorchain Savers

src/common/utxobased/db/makeBaselets.ts, src/common/utxobased/db/makeProcessor.ts, src/common/utxobased/db/types.ts, src/common/utxobased/engine/makeUtxoEngineState.ts
- fixed: Correctly report balances for old Airbitz-created wallets.
- changed: Automatically delete wallet caches if they becomes corrupted on disk, such as from a failed resync.
This also does a few internal code cleanups I found while debugging.
---
- https://app.asana.com/0/0/1203426224270514
=> Fix balance bug & friends

src/common/utxobased/info/bitcoin.ts, src/common/utxobased/info/bitcointestnet.ts, src/common/utxobased/info/litecoin.ts
---
- https://app.asana.com/0/0/1203582095834056
=> Add RBF flags for Bitcoin and Litecoin

src/common/plugin/makeCurrencyTools.ts, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/engine/makeUtxoEngineState.ts, src/common/utxobased/engine/utils.ts, src/common/utxobased/keymanager/cleaners.ts, test/common/utxobased/engine/engine.spec.ts
- https://github.com/EdgeApp/edge-core-js/pull/494
---
- https://app.asana.com/0/0/1203136033933205
=> Support bech32 addresses

src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/qtum.ts, src/common/utxobased/info/ravencoin.ts
---
- https://app.asana.com/0/0/1203495785463918
=> Remove old blockbook servers hosted on edge.app that no longer exist

package.json
- Fixed: Incorrect types path in package.json
=> Fix incorrect types path in package.json

src/common/fees/makeFees.ts
---
- https://app.asana.com/0/0/1204334418189086
=> Query networkFees with pluginId instead of currencyCode

src/common/utxobased/keymanager/keymanager.ts, test/common/utxobased/keymanager/coins/altcointestfixtures.ts, test/common/utxobased/keymanager/coins/keymanagertest.spec.ts
Added: Support for pay-to-taproot address support (P2TR) for Bitcoin wallets.
none
none
---
- https://app.asana.com/0/0/1202005495719290
=> Pay-to-Taproot (P2TR) Address Support for Bitcoin

package.json, src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/engine/makeUtxoEngine.ts, test/common/utxobased/engine/engine.spec.ts, yarn.lock
- changed: Upgrade to edge-core-js v1.4.1
none
none
---
- https://app.asana.com/0/0/1205340223134609
=> Upgrade core

CHANGELOG.md, src/common/utxobased/engine/makeUtxoEngine.ts, src/common/utxobased/info/litecoin.ts
none
none
---
- https://app.asana.com/0/0/1205888764853628
=> Add missing check for currency RBF capabilities in accelerate method

CHANGELOG.md, src/common/utxobased/keymanager/utxopicker/subtractFee.ts
none
none
---
- https://app.asana.com/0/0/1205650008943215
=> Check fee amount compared to inputs for `subtractFee` style transactions

CHANGELOG.md, src/common/utxobased/engine/ServerStates.ts, src/common/utxobased/engine/UtxoEngineState.ts, src/common/utxobased/network/Blockbook.ts, src/common/utxobased/network/BlockbookElectrum.ts, src/common/utxobased/network/Socket.ts, src/common/utxobased/network/blockbookApi.ts, src/common/utxobased/network/electrumApi.ts
none
none
---
- https://app.asana.com/0/0/1206639139959668
=> Electrum Connection Support (UTXO data only)

CHANGELOG.md, README.md, src/react-native.ts, webpack.config.js
=> Change webpack dev-server port from 8081 to 8084

CHANGELOG.md, src/common/utxobased/db/Models/ProcessorTransaction.ts, src/common/utxobased/db/types.ts, src/common/utxobased/engine/UtxoEngine.ts, src/common/utxobased/engine/UtxoEngineState.ts, src/common/utxobased/keymanager/utxopicker/types.ts, src/common/utxobased/network/blockbookApi.ts, test/common/utxobased/db/Processor.spec.ts
none
none
---
- https://app.asana.com/0/0/1206094286272292
=> Check input sequence values for RBF flag

README.md, docs/currency-integration.md, src/common/plugin/CurrencyTools.ts, src/common/plugin/types.ts, src/common/plugin/utils.ts, src/common/utxobased/engine/UtxoEngine.ts, src/common/utxobased/info/badcoin.ts, src/common/utxobased/info/bitcoin.ts, src/common/utxobased/info/bitcoincash.ts, src/common/utxobased/info/bitcoincashtestnet.ts, src/common/utxobased/info/bitcoingold.ts, src/common/utxobased/info/bitcoingoldtestnet.ts, src/common/utxobased/info/bitcoinsv.ts, src/common/utxobased/info/bitcointestnet.ts, src/common/utxobased/info/dash.ts, src/common/utxobased/info/digibyte.ts, src/common/utxobased/info/dogecoin.ts, src/common/utxobased/info/eboost.ts, src/common/utxobased/info/feathercoin.ts, src/common/utxobased/info/groestlcoin.ts, src/common/utxobased/info/litecoin.ts, src/common/utxobased/info/qtum.ts, src/common/utxobased/info/ravencoin.ts, src/common/utxobased/info/smartcash.ts, src/common/utxobased/info/ufo.ts, src/common/utxobased/info/vertcoin.ts, src/common/utxobased/info/zcoin.ts, src/common/utxobased/keymanager/cleaners.ts, test/utils.ts
none
none
---
- https://app.asana.com/0/0/1207448132629911
=> Add currency contribution guide and documentation

CHANGELOG.md, package.json, src/common/utxobased/engine/UtxoEngine.ts, src/common/utxobased/engine/types.ts, yarn.lock
none
none
---
- https://app.asana.com/0/0/1207517164181978
=> Use new `enableRbf` field on EdgeSpendInfo

CHANGELOG.md, src/common/utxobased/info/litecoin.ts, test/common/plugin/CurrencyPlugin.fixtures/currencies/litecoin.ts
https://github.com/EdgeApp/edge-react-gui/pull/5094
none
---
- https://app.asana.com/0/0/1207269774668901
=> Support ltc->btc split

CHANGELOG.md, src/common/utxobased/engine/UtxoEngine.ts
none
none
---
- https://app.asana.com/0/0/1208249018135757
=> Fix sweepPrivateKey transaction amount for UTXO currencies

CHANGELOG.md, src/common/plugin/PluginState.ts
none
none
---
- https://app.asana.com/0/0/1207859097985661
=> Force enableCustomServers to false server list is empty

CHANGELOG.md, src/common/utxobased/info/bitcoincash.ts
---
- https://app.asana.com/0/0/1207604271105266
=> Remove unreliable bitcoincash xpub  link

CHANGELOG.md, src/common/plugin/CurrencyPlugin.ts, src/common/plugin/PluginState.ts, src/common/plugin/types.ts, src/common/utxobased/engine/UtxoEngine.ts, src/common/utxobased/engine/UtxoEngineProcessor.ts, src/common/utxobased/network/blockbookApi.ts
- **Fix broken cleaner for atomicwallet.io**
- **Implement updateInfoPayload**
- **Simplify options for EngineConfig**
none
none
---
- https://app.asana.com/0/0/1208931449878115
=> Implement updateInfoPayload

CHANGELOG.md, src/common/utxobased/info/ravencoin.ts
none
none
---
- https://app.asana.com/0/0/1209803413515028
=>  Update Ravencoin block explorer

CHANGELOG.md, src/common/utxobased/info/all.ts, src/common/utxobased/info/bitcointestnet4.ts
none
none
---
- https://app.asana.com/0/0/1209863798532473
=> Add Bitcoin Testnet4 support

CHANGELOG.md, src/common/utxobased/info/qtum.ts
none
none
---
- https://app.asana.com/0/0/1209323796613842
=> Add Qtum blockbook server endpoints

CHANGELOG.md, src/common/utxobased/info/zcoin.ts
none
none
---
- https://app.asana.com/0/0/1210369133172718
=> Remove nownodes blockbook server for FIRO
