EdgeApp/edge-currency-plugins

src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/makeCurrencyTools.ts
src/common/plugin/types.ts
src/common/utxobased/info/bitcoin.ts
src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/keymanager/coins/bitcoin.spec.ts
test/common/utxobased/keymanager/coins/bitcoincash.spec.ts
test/common/utxobased/keymanager/coins/bitcoingold.spec.ts
test/common/utxobased/keymanager/coins/bitcoinsv.spec.ts
test/common/utxobased/keymanager/coins/dash.spec.ts
test/common/utxobased/keymanager/coins/decred.spec.ts
test/common/utxobased/keymanager/coins/digibyte.spec.ts
test/common/utxobased/keymanager/coins/dogecoin.spec.ts
test/common/utxobased/keymanager/coins/eboost.spec.ts
test/common/utxobased/keymanager/coins/feathercoin.spec.ts
test/common/utxobased/keymanager/coins/groestlcoin.spec.ts
test/common/utxobased/keymanager/coins/litecoin.spec.ts
test/common/utxobased/keymanager/coins/qtum.spec.ts
test/common/utxobased/keymanager/coins/ravencoin.spec.ts
test/common/utxobased/keymanager/coins/smartcash.spec.ts
test/common/utxobased/keymanager/coins/ufo.spec.ts
test/common/utxobased/keymanager/coins/vertcoin.spec.ts
test/common/utxobased/keymanager/coins/zcash.spec.ts
test/common/utxobased/keymanager/coins/zcoin.spec.ts

This adds support to create a new wallet by creating a new random private key (mnemonic).
When creating a new private key, we want to allow an options parameter to override the default values to generate a new wallet. If no overrides are passed, we grab `foramt` and `coinType` values from the currency info data but if no values are present using default values.
According to the specs for [Edge key formats](https://github.com/EdgeApp/edge-core-js/blob/master/docs/key-formats.md) private and public keys should be stored with specific keys.

Create Private Key

---

src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/keymanager/coins/bitcoin.spec.ts
test/common/utxobased/keymanager/coins/bitcoincash.spec.ts
test/common/utxobased/keymanager/coins/bitcoingold.spec.ts
test/common/utxobased/keymanager/coins/bitcoinsv.spec.ts
test/common/utxobased/keymanager/coins/cashaddr.spec.ts
test/common/utxobased/keymanager/coins/dash.spec.ts
test/common/utxobased/keymanager/coins/decred.spec.ts
test/common/utxobased/keymanager/coins/digibyte.spec.ts
test/common/utxobased/keymanager/coins/dogecoin.spec.ts
test/common/utxobased/keymanager/coins/eboost.spec.ts
test/common/utxobased/keymanager/coins/feathercoin.spec.ts
test/common/utxobased/keymanager/coins/groestlcoin.spec.ts
test/common/utxobased/keymanager/coins/litecoin.spec.ts
test/common/utxobased/keymanager/coins/qtum.spec.ts
test/common/utxobased/keymanager/coins/ravencoin.spec.ts
test/common/utxobased/keymanager/coins/smartcash.spec.ts
test/common/utxobased/keymanager/coins/ufo.spec.ts
test/common/utxobased/keymanager/coins/vertcoin.spec.ts
test/common/utxobased/keymanager/coins/zcash.spec.ts
test/common/utxobased/keymanager/coins/zcoin.spec.ts

When a seed or mnemonic is passed in to the keymanager, it should be using the `base64` encoding when casting to a `Buffer`

seedOrMnemonicToXPriv to encode with base64

---

src/common/utxobased/db/Models/baselet.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/db/types.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

Due to the realization of needing to store the address data by the script pubkey, the database structure has been slightly modified. 
* Script pubkeys are the only thing stored by an address' path
* Address data is now stored by the script pubkey
* Fetch/update functions have been fixed appropriately

Address Database Refactor

---

src/common/utxobased/network/BlockBook.ts

It fixes the `BLOCK_HEIGHT_CHANGED` callback when listening for new blocks to only emit the height value.

Fix BlockBook New Block Callback

---

src/common/utxobased/db/makeProcessor.ts

It will calculate a transaction amount using data that is already in memory instead of adding a task to the queue to update the transaction after calculating the amount.

Calculate Transaction Amount Without Queue

---

src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

It changes the processor api for saving/updating an address by returning promises and not adding anything to the queue.

Update Processor Address API

---

src/common/utxobased/engine/utils.ts

It only checks if the wallet type is `Segwit` to know if it needs to also derive keys for `WrappedSegwit`

Dynamically derive xpriv from wallet keys.

---

src/common/utxobased/db/Models/baselet.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/network/BlockBook.ts
src/common/utxobased/network/Socket.ts
test/common/utxobased/db/Processor.spec.ts
test/common/utxobased/network/BlockBook.spec.ts

To facilitate the tracking of e.g. unconfirmed transactions an additional RangeBase is created to keep track of transaction id's by
block height.  A RangeBase was chosen to enable extension of its functionality into tracking non-matured transactions. In such a scenario each coin would have a maturity limit. This would also make it easier to detect and track transaction re-orgs.
If a new transaction is saved to the transaction base with a block height of 0, its txid is added to the range base with block height 0.
Upon each incoming block notification all txids in the block height range base with a block height of 0 are fetched. For each of them, their transaction data is re-fetched from Blockbook and compared with their existing saved transaction. If its block height is changed, the new …

Update block height of unconfirmed transactions

---

src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/paymentRequest.ts
test/common/utxobased/engine/PaymentRequest.spec.ts

This is a port of the old plugin behavior to the new plugin. The old plugin had additional address sanity checks and converted addresses to legacy format. These additional steps are dropped. Some redundant arguments in create payment were also dropped.

Engine: Add json payment protocol options

---

fixtures/currencyPlugins.json
test/common/plugin/currencyPlugins.spec.ts

The tests should expect `legacyAddress` when parsing Litecoin `3` addresses.

Fix parseUri Test

---

src/common/utxobased/engine/makeUtxoEngineState.ts

Transaction data returned from BlockBook can have the `blockHeight` value of `-1`. Because in Edge, `-1` means dropped and `0` means pending, a new pending transaction shows as being dropped rather than pending.
When processing raw tx data from BlockBook, checking if the `blockHeight < 0` and then setting it to `0`

Fix Pending Tx Showing Dropped

---

src/common/utxobased/db/Models/ProcessorTransaction.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/types.ts
src/common/utxobased/keymanager/keymanager.ts
src/common/utxobased/keymanager/utxopicker/accumulative.ts
src/common/utxobased/keymanager/utxopicker/types.ts
test/common/utxobased/keymanager/coins/bitcoincashtransactiontest.spec.ts
test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts
test/common/utxobased/keymanager/coins/groestlcointransactiontest.spec.ts

After signing a transaction, we return the transaction which is in turn passed to `engine.saveTransaction()`. Previously, the `txid` was not being set. Since in order to calculate the txid, the full transaction needs to be signed, we should set the id when we set the `signedTx` value on the `EdgeTransaction` as well.
Also going from an `EdgeTransaction` to `ProcessorTransaction` was not preserving the `signedTx` or `hex` value.

Signed Transaction Id

---

src/common/utxobased/db/Models/ProcessorTransaction.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

The function `fetchTransactions` did not properly fetch data from the database. If no params from the function arguments match, return all transaction in the db. Also because an `EdgeTransaction` has a parameter `ourReceiveAddresses` I remap the values stored in the db for `ourOuts` to get the `scriptPubkey` from the db and convert it to the addresses expected.

Fetch Transactions Fix

---

src/common/plugin/utils.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngine.ts
test/common/utxobased/db/Processor.spec.ts

This pull request builds largely on @passabilities original work, adding functionality to the current makeUtxoEngine `resyncBlockchain` function stub. All data in the baselets is now retained in an additional top-level disklet that is itself subdir'ed from the original passed in disklet. This should ensure that only the data of the resyncing blockchain is deleted.
To test its functionality, an address is added to the baselets and then removed with the new clearAll function.

Resync blockchain

---

src/common/plugin/types.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoWalletTools.ts
src/common/utxobased/keymanager/keymanager.ts
src/common/utxobased/keymanager/utxopicker.ts
src/common/utxobased/keymanager/utxopicker/subtractFee.ts

Based on #73 and #74.
Sweep private key is implemented in the UtxoEngine's sweepPrivateKey function. To facilitate fetching the to be spent utxos, a temporary engine state is created. The UtxoEngineState emitter is in turn used as a callback to notify when all addresses have been scanned. The callback then resolves the Promise of the sweepPrivateKey function. On success, it returns an unsigned EdgeTransaction.
To support sweepPrivateKey, additional changes were done in the wallet tools to support wif keys and the keymanager to support creating transactions with pre-selected UTXOs.

Sweep private key

---

src/common/plugin/types.ts
src/common/utxobased/engine/makeUtxoEngine.ts

Fixes types in `signTx` that defaults the `paymentProtocolInfo` to an empty object.

Fixing SignTx Payment Protocol Info

---

src/common/utxobased/engine/makeUtxoEngine.ts

It adds a check to `makeUtxoEnigne` that verifies the `walletInfo.keys.format` is a valid format listed in the `currencyInfo.formats` array.

Verify Engine Format

---

src/common/plugin/types.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/network/BlockBook.ts
src/common/utxobased/network/Socket.ts
src/common/utxobased/network/nodejsWS.ts
src/common/utxobased/network/socketQueue.ts
src/common/utxobased/network/types.ts
src/common/utxobased/network/windowWS.ts
test/common/utxobased/network/BlockBook.spec.ts

Based on #73 
Refactors the Socket and Blockbook functions to be more like the networking code of the old, battle-tested edge-currency-bitcoin plugin.
This commit is meant as pre-cursor work to lay the foundation for a task queue and multiple sockets.
The new networking code is designed to use fewer callbacks and more promises and events, favors maps over objects with dynamic keys, has a more robust keep alive / heartbeat system that takes existing queries into account, has a cleaner subscription interface and allows for the potential usage of a task queue and multiple sockets.
Further, some more error handling is introduced, though this will need further improvement.
Some more test cases in the block book tests are added to test these new capabilities. Note that this work does not change …

Network refactor

---

.eslintrc.json
src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/makeEngineEmitter.ts
src/common/plugin/types.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/network/BlockBook.ts
src/common/utxobased/network/Socket.ts
test/common/utxobased/db/Processor.spec.ts
test/common/utxobased/network/BlockBook.spec.ts

It creates an `Emitter` object that is specific to the use cases of the engine events.

EngineEmitter

---

src/common/utxobased/db/makeBaselets.ts
src/common/utxobased/db/makeProcessor.ts

It creates an object that creates/opens the baselet objects for the processor. 
It enables being able to mutex a table category for the processor (address, transaction and utxo)

Make Baselets

---

package.json
src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/makeEngineEmitter.ts
src/common/plugin/makeMetadata.ts
src/common/plugin/utils.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
test/common/plugin/makeMetadata.spec.ts
yarn.lock

It creates a metadata object that listens to events from the engine and updates the wallet balance.
It listens for an event when an address balance changes and mutexes updating the wallet balance.
It reduces code duplication when sweeping a private key for the emitter.

Make Metatdata

---

src/common/utxobased/network/BlockBook.ts
test/common/utxobased/network/BlockBook.spec.ts

Tests are currently broken, because a `backend` field was added to the blockbook `fetchinfo` call.

Fetch info fix

---

package.json

Mocha does not exit if some asynchronous processes are not done yet.
This behavior is now overridden with the --exit flag.

Exit mocha after tests complete

---

.github/workflows/build.yml

Currently fails because of the broken tests and lint.

Add Github Actions CI

---

src/common/utxobased/engine/makeUtxoEngineState.ts

Changes to run in commit 28ee922ede1e669f613156be7a2f70a08c680961 never set the state to false again.

EngineState: Set running=false when stopping

---

src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/pluginState.ts
src/common/plugin/serverCache.ts
src/common/plugin/types.ts
src/common/utxobased/engine/constants.ts
src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/network/BlockBook.ts
src/common/utxobased/network/Socket.ts
src/common/utxobased/network/socketQueue.ts
test/common/utxobased/network/BlockBook.spec.ts

Just opened for visibility, review has to wait until PickNextTask is merged.
Add support for multiple sockets. This introduces more caches for each of the sockets, a plugin state object that holds servers in a queue and code to select servers for connections by their score.

Multi socket

---

src/common/plugin/makeMetadata.ts
src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

Fixes to the metadata cache to update the balance correctly when starting a resync and the serverCache to clear any lingering data and connections.

Fix resync behavior

---

src/common/plugin/types.ts
src/common/utxobased/db/Models/baselet.ts
src/common/utxobased/db/makeBaselets.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/keymanager/keymanager.ts
src/common/utxobased/keymanager/utxopicker.ts
src/common/utxobased/keymanager/utxopicker/forceUseUtxo.ts
src/common/utxobased/keymanager/utxopicker/subtractFee.ts
src/common/utxobased/keymanager/utxopicker/types.ts

Uses an interim UTXO data structure to keep hold of the already spent
UTXOs. They are removed again once a transaction confirms, and are added
when a transaction is broadcast.
Adds another fee strategy that allows the caller to force usage of a
certain array of UTXOs.

RBF Support

---

src/common/plugin/makeEngineEmitter.ts
src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/network/BlockBook.ts
src/common/utxobased/network/MakeSocketEmitter.ts
src/common/utxobased/network/Socket.ts
test/common/utxobased/network/BlockBook.spec.ts

The EngineEmitter is split into an emitter that actually only handles
events in either engine/server states and an emitter that uniquely
handles socket events.

SocketEmitter: Split socket specific events from Engine

---

src/common/utxobased/engine/makeUtxoEngineState.ts

Resolving the write promises all at once led to an inconsistency bug: After stopping and starting the engine multiple UTXOs belonging to the same scriptPubkey were counted twice.
Resolving them piecemeal resolved the bug.

EngineState: Replace Promise.all in balance calculation

---

src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

Also ended up fixing an off-by-one error in the setLookAhead while loop.
The initial conditions and last valid iteration, around the edges
of the control logic in the while loop with gap limit 20 are now:
```
lastUsed: -1 , addressCount: 0 => -1 + 20 >= 19
lastUsed: 0, addressCount: 0 => 0 + 20 >= 20
```

Fix lastUsed function signature

---

package.json

Runs `npx sort-package-json` to follow the sorting rules according to this package.

Sort package.json to fix browser field location

---

package.json
src/common/utxobased/db/Models/baselet.ts
src/common/utxobased/db/makeBaselets.ts
src/common/utxobased/db/makeProcessor.ts
src/common/utxobased/db/types.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/util/filterUndefined.ts
test/common/utxobased/db/Processor.spec.ts
yarn.lock

This upgrades baselet to the new branch which includes type safety on all types of baselets. Includes necessary changes to the processor and engine with the added type safety/coverage.
Replaces: https://github.com/EdgeApp/edge-currency-plugins/pull/181

Upgrade baselet

---

src/common/plugin/pluginState.ts
src/common/plugin/serverCache.ts

This fixes a few issues with the server state:
1. Memlet's return value was incorrectly assumed to be a JSON string; remove the extra JSON parsing.
2. Add cleaners for the serverCache.json file data object.
3. Add cleaners for the info server network responses for the server lists.

Server state fixes

---

src/bch.ts
src/bsv.ts
src/btc.ts
src/common/fees/makeFees.ts
src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/makeCurrencyTools.ts
src/common/plugin/types.ts
src/common/plugin/utils.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/info/bitcoin.ts
src/common/utxobased/info/bitcoincash.ts
src/common/utxobased/info/bitcoinsv.ts
src/common/utxobased/info/bitcointestnet.ts
src/common/utxobased/info/feathercoin.ts
src/common/utxobased/info/litecoin.ts
src/common/utxobased/info/zcoin.ts
src/firo.ts
src/ftc.ts
src/index.ts
src/ltc.ts
src/tbtc.ts
test/common/fees/fees.spec.ts
test/utils.ts

Refactor EngineCurrencyInfo for each wallet to no longer extend EdgeCurrencyInfo. Rather, have EngineInfo and EdgeCurrencyInfo be sibling fields in a PluginInfo object which is passed to makeCurrencyPlugin.

Refactor EngineCurrencyInfo

---

src/common/utxobased/engine/makeServerStates.ts

This hasty invocation side-steps the proper invocation flow beginning
with the `startEngine` method.

Sam/Fix/Hasty Refill Servers

---

fixtures/currencyPlugins.json
src/common/utxobased/info/all.ts
src/common/utxobased/info/badcoin.ts
src/common/utxobased/info/bitcoingold.ts
src/common/utxobased/info/dash.ts
src/common/utxobased/info/digibyte.ts
src/common/utxobased/info/dogecoin.ts
src/common/utxobased/info/eboost.ts
src/common/utxobased/info/groestlcoin.ts
src/common/utxobased/info/qtum.ts
src/common/utxobased/info/ravencoin.ts
src/common/utxobased/info/smartcash.ts
src/common/utxobased/info/ufo.ts
src/common/utxobased/info/vertcoin.ts

This adds the remaining missing currency info files from edge-currency-bitcoin. The info for for the following currencies have been added:
* badcoin BAD
* bitcoingold BTG
* dash DASH
* digibyte DGB
* dogecoin DOGE
* eboost EBST
* groestlcoin GRS
* qtum QTUM
* ravencoin RVN
* smartcash SMART
* ufo UFO
* vertcoin VTC

Add Currency Info

---

src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/pluginState.ts
src/common/plugin/serverScores.ts
src/common/utxobased/engine/makeServerStates.ts
test/common/plugin/serverScores.spec.ts

This removes the in-memory cache from the server state and re-implements the logic in the plugin state. The server state file is renamed to server scores. 
---
- https://app.asana.com/0/0/1199373123392598

Server Score / Plugin State refactor

---

src/common/plugin/makeCurrencyTools.ts
src/common/plugin/types.ts
src/common/plugin/utils.ts
src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/engine/makeUtxoWalletTools.ts
src/common/utxobased/engine/utils.ts
src/common/utxobased/keymanager/cleaners.ts
test/common/utxobased/engine/UtxoWalletTools.spec.ts

Re-implement `derivePublicKey` to follow `edge-core-js` key-formats spec
- Add PrivateKey and PublicKey types and asPrivateKey and asPublicKey
cleaners for internal use and documentation.
- Desensitize public keys returned by derivePublicKey using the cleaners.
- Modify util functions to always include segwit and wrapped-segwit
formats together, following the spec.
---
- https://app.asana.com/0/0/1201256727099457

Sam/Fix/Numb Keys

---

src/common/plugin/types.ts
src/common/utxobased/info/dogecoin.ts
src/common/utxobased/info/utxoPickers/dogeUtxoPicker.ts
src/common/utxobased/keymanager/keymanager.ts
src/common/utxobased/keymanager/utxopicker.ts
src/common/utxobased/keymanager/utxopicker/accumulative.ts
src/common/utxobased/keymanager/utxopicker/forceUseUtxo.ts
src/common/utxobased/keymanager/utxopicker/subtractFee.ts
src/common/utxobased/keymanager/utxopicker/types.ts
src/common/utxobased/keymanager/utxopicker/utils.ts

Dogecoin has a min relay fee of 0.001 Doge / KByte according to their newest fee scheme described in
https://github.com/dogecoin/dogecoin/discussions/2347 . Enforce this by adding a fee checker function to the CoiInfo.
---
- https://app.asana.com/0/0/1201274042339100

Dogecoin: Add min relay fee rate

---

src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

Remove an unused `engineStarted` flag to fix the reconnect
implementation.
---
- https://app.asana.com/0/0/1201681616582368

Fix broken reconnect for makeServerStates

---

src/common/plugin/makeCurrencyTools.ts
test/common/plugin/currencyPlugin.fixtures/common.ts
test/common/plugin/currencyPlugin.fixtures/currencies/bitcoin.ts
test/common/plugin/currencyPlugin.fixtures/currencies/bitcoincash.ts
test/common/plugin/currencyPlugin.fixtures/currencies/bitcoinsv.ts
test/common/plugin/currencyPlugin.fixtures/currencies/digibyte.ts
test/common/plugin/currencyPlugin.fixtures/currencies/feathercoin.ts
test/common/plugin/currencyPlugin.fixtures/currencies/groestlcoin.ts
test/common/plugin/currencyPlugin.fixtures/currencies/litecoin.ts
test/common/plugin/currencyPlugin.fixtures/currencies/smartcash.ts
test/common/plugin/currencyPlugin.fixtures/currencies/zcoin.ts

Only support mnemonic phrases for imports and change the error
handling flow to make the business logic more obvious; remove support
for "hex seeds".

Fix `importPrivateKey` error cases and change spec

---

src/index.ts

This allows for the GUI to use the `setMemletConfig` for the correct
module.
This is a problem if the GUI happens to use a different memlet
dependency than what the plugins use.
---
- https://app.asana.com/0/0/1201914705276091

Export `setMemletConfig`

---

test/common/utxobased/network/BlockBook.spec.ts

This is so we don't conflict with a running edge-core-js
webpack-dev-server.
---
- https://app.asana.com/0/0/1201914705276098

Change test websocket server port

---

src/common/utxobased/db/makeProcessor.ts

This remove the requirement for `saveTransaction` to be atomic; it can
safely be interrupted.
---
- https://app.asana.com/0/0/1201924982952951

Index transaction data after the transaction is saved

---

src/common/plugin/makeCurrencyPlugin.ts
src/common/plugin/pluginState.ts
src/common/plugin/utils.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/types.ts
src/common/utxobased/info/badcoin.ts
src/common/utxobased/info/bitcoin.ts
src/common/utxobased/info/bitcoincash.ts
src/common/utxobased/info/bitcoincashtestnet.ts
src/common/utxobased/info/bitcoingold.ts
src/common/utxobased/info/bitcoingoldtestnet.ts
src/common/utxobased/info/bitcoinsv.ts
src/common/utxobased/info/bitcointestnet.ts
src/common/utxobased/info/dash.ts
src/common/utxobased/info/digibyte.ts
src/common/utxobased/info/dogecoin.ts
src/common/utxobased/info/eboost.ts
src/common/utxobased/info/feathercoin.ts
src/common/utxobased/info/groestlcoin.ts
src/common/utxobased/info/litecoin.ts
src/common/utxobased/info/qtum.ts
src/common/utxobased/info/ravencoin.ts
src/common/utxobased/info/smartcash.ts
src/common/utxobased/info/ufo.ts
src/common/utxobased/info/vertcoin.ts
src/common/utxobased/info/zcoin.ts
test/common/utxobased/engine/engine.fixtures/bitcoinTestnet/tests.ts

We don't want to read old electrum settings from the old plugin, since those won't work. We also want to change `disableFetchingServers` into the less-confusing `enableCustomServers`.

Update the `userSettings` format

---

src/common/utxobased/db/Models/ProcessorTransaction.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts

Computes the sat/vByte used for a given transaction, and adds
`feeRateUsed` object to the `EdgeTransaction` output.
The frontend should be able to render the transaction fee information
for received transactions. However, it only works for new transactions.
To make existing transactions also display the UTXO fees, changes need
to be made in the `edge-core-js` repository to modify the cache fetching
and merging logics.
See associated branch: https://github.com/EdgeApp/edge-core-js/tree/xipu/btc-receive-fee
---
- https://app.asana.com/0/0/1200681747993915

Build feeRateUsed for frontend consumption

---

src/common/plugin/makeCurrencyTools.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/utils.ts
src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/keymanager/coins/bitcoincashtransactiontest.spec.ts
test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts
test/common/utxobased/keymanager/coins/groestlcointransactiontest.spec.ts

The added logics check if the `target` has memo, if so, we know it's 
an `OP_RETURN` script. Then, we use the altcoin.js lib to construct
an `OP_RETURN` script value.
However, if the memo (in hex string) exceeds the 80 bytes limitation
for `OP_RETURN` script, we throw.
---
- https://app.asana.com/0/0/1201934696774649

Add OP_RETURN to outputs

---

src/common/utxobased/keymanager/keymanager.ts

We include strings with only space characters as "empty strings".
---
- https://app.asana.com/0/0/1202829098136863

Filter for empty strings in SpendTarget memo

---

src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/keymanager/coins/bitcoincashtransactiontest.spec.ts
test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts
test/common/utxobased/keymanager/coins/groestlcointransactiontest.spec.ts

Allows sorting by bip69 convention or in order of targets passed in with change as last output.
Unit tests verified by decoding signedTx using web decoder to ensure outputs are properly sorted given the outputSort param value.
---
- https://app.asana.com/0/0/1202844141125919

Add outputSort param to makeSpend

---

src/common/plugin/types.ts
src/common/utxobased/db/Models/ProcessorTransaction.ts
src/common/utxobased/db/types.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/info/dash.ts
src/common/utxobased/network/BlockBookAPI.ts

The "transaction specific" blockbook functionality include additional data that is unique to the network the transaction is on. For example, this is where Dash's InstantSend boolean is returned since that wouldn't be appropriate in the general transaction endpoint. 
This PR adds the following:
1) Add transaction specific functionality
2) Use new endpoint and the core's confirmation API to update pending InstantSend transactions as confirmed
3) Add logic to avoid the extra query and engine callback if the plugin doesn't require the new method
---
- https://app.asana.com/0/0/1201425242712367

Add getTransactionSpecific endpoint support

---

src/common/utxobased/network/Socket.ts

This is to prevent a race condition where the timeout for some blockbook
server connection is the same as the heartbeat; our heartbeat time must
be lower than the server timeout.
---
- https://app.asana.com/0/0/1203495785463912

Reduce the KEEP_ALIVE_MS blockbook server heartbeat time

---

package.json
src/common/plugin/makeCurrencyTools.ts
src/common/utxobased/engine/makeServerStates.ts
src/common/utxobased/engine/makeUtxoEngine.ts
src/common/utxobased/engine/makeUtxoEngineState.ts
src/common/utxobased/engine/types.ts
src/common/utxobased/engine/utils.ts
src/common/utxobased/keymanager/cleaners.ts
test/common/utxobased/engine/engine.spec.ts
yarn.lock

- changed: Upgrade security access to private keys in EdgeWalletInfo
- changed: Add signMessage API to replace signMessageBase64 in otherMethods
---
- https://app.asana.com/0/0/1204056629741203

Only handle private keys within privileged functions

---

src/common/utxobased/engine/makeUtxoEngine.ts

- fixed: Bug with signMessage cleaning of `EdgeSignMessageOptions['otherParams']`
none
none

Fix otherParams for signMessage

---

src/common/utxobased/engine/makeUtxoEngine.ts

- Fixed: Throw DustSpendError instead of obscure blockbook error message for dust spend transaction broadcasts.
none
none
---
- https://app.asana.com/0/0/1204859092318979

Detect and throw DustSpendError

---

src/common/utxobased/info/bitcoincash.ts

BSV is currently disabled, so shouldn't be able to split into it.
- removed: BSV from BCH's split options
none
none
---
- https://app.asana.com/0/0/1205443361322801

Remove BSV from BCH's split options

---

CHANGELOG.md
src/common/fees/makeFees.ts
src/common/plugin/types.ts

In order to apply defaults to new entry additions to the FeeInfo type
(such as 'maximumFeeRate') without the fee info from disk/info-server
overwriting, we must apply the fallback values at the cleaner level.
none
none
---
- https://app.asana.com/0/0/1205823029134351

Add optional fallback generic parameter to asFeeInfo cleaner

---

CHANGELOG.md
src/common/utxobased/engine/makeUtxoEngine.ts

---
- https://app.asana.com/0/0/1206302598410433

Disable accelerate for legacy bip32 Airbitz wallets

---

CHANGELOG.md
src/common/utxobased/engine/makeUtxoEngine.ts

---
- https://app.asana.com/0/0/1206437518749021

Disable accelerate for bip44 wallets

---

CHANGELOG.md
src/common/utxobased/keymanager/utxopicker/subtractFee.ts

---
- https://app.asana.com/0/0/1206447703476989

Account for potentially NaN sum in subtractFee

---

CHANGELOG.md
package.json
src/common/utxobased/db/Processor.ts
yarn.lock

none
none
---
- https://app.asana.com/0/0/1206774067464215

Fix for "Missing processor address" error

---

src/common/utxobased/info/badcoin.ts
src/common/utxobased/info/bitcoin.ts
src/common/utxobased/info/bitcoincash.ts
src/common/utxobased/info/bitcoincashtestnet.ts
src/common/utxobased/info/bitcoingold.ts
src/common/utxobased/info/bitcoingoldtestnet.ts
src/common/utxobased/info/bitcoinsv.ts
src/common/utxobased/info/bitcointestnet.ts
src/common/utxobased/info/commonInfo.ts
src/common/utxobased/info/dash.ts
src/common/utxobased/info/digibyte.ts
src/common/utxobased/info/dogecoin.ts
src/common/utxobased/info/eboost.ts
src/common/utxobased/info/feathercoin.ts
src/common/utxobased/info/groestlcoin.ts
src/common/utxobased/info/litecoin.ts
src/common/utxobased/info/qtum.ts
src/common/utxobased/info/ravencoin.ts
src/common/utxobased/info/smartcash.ts
src/common/utxobased/info/ufo.ts
src/common/utxobased/info/vertcoin.ts
src/common/utxobased/info/zcoin.ts

none
It turns out we already had fee templates in here, so I just reorganized things to match edge-currency-accountbased a bit more.
---
- https://app.asana.com/0/0/1206994839543313

Currency info cleanup

---

.eslintignore
.gitignore
.nycrc.json
.travis.yml
CHANGELOG.md
README.md
android/build.gradle
android/format-java.sh
android/src/main/AndroidManifest.xml
android/src/main/java/app/edge/reactnative/currencyplugins/EdgeCurrencyPluginsModule.java
android/src/main/java/app/edge/reactnative/currencyplugins/EdgeCurrencyPluginsPackage.java
config.sample.json
edge-currency-plugins.d.ts
edge-currency-plugins.podspec
ios/EdgeCurrencyPluginsModule.m
ios/EdgeCurrencyPluginsModule.swift
ios/edge-currency-plugins.xcodeproj/project.pbxproj
package.json
src/common/plugin/CurrencyPlugin.ts
src/declare-modules.d.ts
src/index.ts
src/react-native.ts
src/types.ts
test/common/plugin/CurrencyPlugin.spec.ts
test/common/utxobased/engine/engine.spec.ts
test/utils.ts
tsconfig.json
webpack.config.js
yarn.lock

none
none
---
- https://app.asana.com/0/0/1207103682121388

Webpack into native module

---

CHANGELOG.md
src/common/plugin/PluginState.ts
src/common/plugin/ServerScores.ts
src/common/utxobased/engine/ServerStates.ts
src/common/utxobased/network/Socket.ts
src/common/utxobased/network/types.ts
src/common/utxobased/network/windowWS.ts

none
none
---
- https://app.asana.com/0/0/1207816094830396

Plugin State Fixes

---

src/common/plugin/PluginState.ts
src/common/plugin/types.ts
src/common/utxobased/db/DataLayer.ts
src/common/utxobased/db/Models/TransactionData.ts
src/common/utxobased/db/Models/baselet.ts
src/common/utxobased/db/types.ts
src/common/utxobased/db/util/utxo.ts
src/common/utxobased/engine/UtxoEngine.ts
src/common/utxobased/engine/UtxoEngineProcessor.ts
src/common/utxobased/engine/UtxoEngineState.ts
src/common/utxobased/engine/util/getOwnUtxosFromTx.ts
src/common/utxobased/engine/utils.ts
src/common/utxobased/info/dash.ts
src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/db/DataLayer.spec.ts
test/common/utxobased/engine/engine.spec.ts
test/common/utxobased/keymanager/coins/bitcointransactiontest.spec.ts
test/common/utxobased/network/Blockbook.spec.ts

none
none
---
- https://app.asana.com/0/0/1207641242793054

Renames for readability

---

CHANGELOG.md
src/common/utxobased/engine/ServerStates.ts
src/common/utxobased/engine/UtxoEngineProcessor.ts
src/common/utxobased/network/Blockbook.ts
src/common/utxobased/network/BlockbookElectrum.ts
src/common/utxobased/network/Socket.ts
test/common/utxobased/network/Blockbook.spec.ts

The goal of this PR is to improve the readablity and maintainability of the pickNextTask routine in UtxoEngineProcessor. This is done by removing unnecessary code decoupling and bringing routine code closer together while fixing any issues discovered during this audit. And last but not least, replacing Deferred promises with the more appropriate use of generators.
I'm not certainly happy with how the types are written for the generator implementation, so please scrutinize that aspect. Additionally, I haven't tested the BlockbookElectrum refactor, so that is an area to look closely at during review.
none
none
---
- …

Improve pickNextTask

---

CHANGELOG.md
src/common/utxobased/info/dash.ts
src/common/utxobased/info/groestlcoin.ts
src/common/utxobased/info/zcoin.ts
src/common/utxobased/network/Socket.ts
src/common/utxobased/network/nodejsWS.ts
src/common/utxobased/network/types.ts
src/common/utxobased/network/windowWS.ts

none
none
---
- https://app.asana.com/0/0/1208118197219322

NowNodes fixes

---

CHANGELOG.md
src/common/utxobased/info/utxoPickers/dogeUtxoPicker.ts

Since Dogecoin Core 1.14.5, the fee rate recommendation has become
0.01 DOGE/kB (https://github.com/dogecoin/dogecoin/releases/tag/v1.14.5).
The prior implementation was wrong to assume `minRelayFeeRate` was units
of DOGE when it should have been sats.
none
none
---
- https://app.asana.com/0/0/1201359074214640

Update DOGE minRelayFeeRate to the recommendation

---

CHANGELOG.md
package.json
src/common/utxobased/db/util/utxo.ts
src/common/utxobased/engine/ServerStates.ts
src/common/utxobased/engine/UtxoEngineProcessor.ts
src/common/utxobased/network/blockbookApi.ts
test/common/utxobased/network/Blockbook.spec.ts
yarn.lock

none
none
---
- https://app.asana.com/0/0/1208670588204693

Block Reward Transaction Support (Coinbase Txs)

---

CHANGELOG.md
src/common/utxobased/engine/UtxoEngineProcessor.ts

We were only updating the checkpoint in response to incoming transactions, which doesn't happen if the phone is already synced. The next incoming transaction after the upgrade will encounter and `undefined` checkpoint, and won't generate a notifiation. Instead, also update the checkpoint when the sync finishes, to ensure that existing accounts will detect incoming funds without needing a full resync.
none
none
---
- https://app.asana.com/0/0/1209313363246606

Fix checkpoint initialization on upgrade

---

CHANGELOG.md
package.json
src/common/utxobased/keymanager/keymanager.ts
test/common/utxobased/keymanager/coins/keymanagertest.spec.ts
yarn.lock

none
none
---
- https://app.asana.com/0/0/1209576495542847

Replace secp256k1 library with bigint compatible version

---

CHANGELOG.md
src/common/utxobased/info/all.ts
src/common/utxobased/info/ecash.ts
test/common/utxobased/addressFormat/addressFormatIndex/fixtures.json
test/common/utxobased/keymanager/coins/altcointestfixtures.ts

none
Changes add eCash (XEC) support to the plugin
---
- https://app.asana.com/0/0/1209816825602433

ecash integration

---

CHANGELOG.md
src/common/plugin/CurrencyPlugin.ts

This is necessary on NodeJS deployments when there's no nativeIo
none
none
---
- https://app.asana.com/0/0/1210778486915222

Fix crash when memletConfig not provided
